version: "3"
services:
  mongo-db:
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
  backend:
    build: "./backend"
    ports:
      - "3333:3333"
    restart: always
